name: Java CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java 14
        uses: joschi/setup-jdk@v2
        with:
          java-version: '14'

      - name: Test version
        run: ./gradlew version

#      - name: Compile
#        run: ./gradlew classes
#
#      - name: Test
#        run: ./gradlew test
#
#      - name: Analyse
#        if: github.ref == 'refs/heads/master'
#        run: ./gradlew version sonarqube -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Djgitver.branch=${GITHUB_REF:11}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
