name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout with all branches and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java 15
        uses: joschi/setup-jdk@v2
        with:
          java-version: '15'

      - name: Compile
        run: ./gradlew classes

      - name: Test
        run: ./gradlew test

#      - name: Publish
#        run: ./gradlew publishToMavenLocal
#        env:
#          USERNAME: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyse
        if: github.ref == 'refs/heads/master'
        run: ./gradlew version sonarqube -Dsonar.login=${{ secrets.SONAR_LOGIN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
