name: SonarQube

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'

      - name: Compile
        run: ./gradlew classes

      - name: Test
        run: ./gradlew test

      - name: Analyse
        if: github.ref == 'refs/heads/master'
        run: ./gradlew version sonarqube -Dsonar.login=${{ secrets.SONAR_LOGIN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
